### PR TITLE
USPS and FedEx Fixes

### PR DESCRIPTION
**Pull request by nahall**
USPS requires the postal code to be set if AcceptanceDateTime is set. For simple rating to an international country, the postal code is irrelevant so this allows more flexibility in rating.

### CODE REVIEW

**Comment by nahall** [comment]
I incorporated a couple more commits for USPS. I've done some testing and so far it seems like USPS is working much better.

**Comment by nahall** [comment]
I also added some predefined FedEx boxes and reworked some that were already in there that weren't correct

**Comment by danh91** [comment]
> I found in testing USPS International that USPS was rejecting some calls due to invalid country name. What was happening was that certain country codes were being passed, "NL" as an example, and then sdk/core/karrio/core/units.py translates that to a country name which in this case was "Netherlands, The". USPS doesn't like that -- the USPS International Mail Manual wants it to just be "Netherlands".
> 
> I went through and edited some of the obvious ones in units.py, like "China, Peoples Republic" becomes just "China" according to the USPS.
> 
> So I tested these and now they work fine, so I put this commit here. But you'll want to think through if that's what you want to do or not as I don't know where you got these country names from, and if other carriers than USPS need them to have different names or not? If every international carrier needs a different name then they may need to be defined per carrier, but I don't know if that's the case or not.
> 
> Also ideally a test should be written that queries the USPS for each one to make sure USPS accepts all the country codes. I just eyeballed a few to change but I'm guessing there are other ones in units.py that USPS would say is invalid, if all of them were tried.

Thanks for those fixes, I took the country list a long time ago from DHL's documentation. Most carriers care mostly about the country code so if USPS reacts to a badly named one, worth fixing it for them.

**Comment by danh91** [comment]
@nahall,

These are really good changes. Let me know when you have something stable would love to merge them often.

**Comment by nahall** [comment]
> @nahall,
> 
> These are really good changes. Let me know when you have something stable would love to merge them often.

OK great, I'm continuing to test (mostly USPS and FedEx) and finding some other little things so I'll keep pushing changes in here as I see issues and at some point things will hopefully be stable for a few days at least.

**Comment by nahall** [comment]
I just put in another commit that you'll have to see if you like or not. I'm not sure I like it myself. Essentially what is happening is that if you ship FedEx One Rate then FedEx returns the One Rate rates but ALSO the non-One Rate rates, all with the same service names. So for example there is FEDEX_2_DAY in there twice -- once for One Rate and once for non-One Rate. Each of them have different rates.

To add more trouble, One Rate has certain rules that the non-One Rate packages don't have. So you really need to know if the rate being returned is One Rate or not. In my case I actually only want One Rate if I'm asking for One Rate, but I can imagine that some other people might want to see both, I'm not sure.

FedEx handles this by returning this "AppliedOptions" field which has a list of options that are set, and the One Rate rate says FEDEX_ONE_RATE for that one.

So my commit handles this by just returning AppliedOptions in the meta field to the caller. This works fine for my program that I'm testing. But I'm just testing with the SDK right now, and you have a pretty clean design and I'm not sure if this is violating how you want to do the architecture between the SDK and the rest of your code.

The other way I thought of doing this is to break One Rate out as separate service types, so there would be FEDEX_ONE_RATE_2_DAY, FEDEX_ONE_RATE_OVERNIGHT, etc, so the SDK could handle everything transparently and callers would just see those different service types. The trouble with that is that FedEx doesn't see them as separate service types so the SDK would need to basically translate between the two, which wouldn't be that hard, but would add more logic in the SDK, for both rate.py and ship.py. I feel like that might be a cleaner solution as then it keeps that logic entirely in the SDK, but it still isn't ideal since it requires inventing new service types that aren't coming directly from FedEx. Ideally FedEx would just break them down into separate service types itself since that's what they should be, instead of calling it an "option", but I doubt that will happen.

**Comment by danh91** [comment]
> I just put in another commit that you'll have to see if you like or not. I'm not sure I like it myself. Essentially what is happening is that if you ship FedEx One Rate then FedEx returns the One Rate rates but ALSO the non-One Rate rates, all with the same service names. So for example there is FEDEX_2_DAY in there twice -- once for One Rate and once for non-One Rate. Each of them have different rates.
> 
> To add more trouble, One Rate has certain rules that the non-One Rate packages don't have. So you really need to know if the rate being returned is One Rate or not. In my case I actually only want One Rate if I'm asking for One Rate, but I can imagine that some other people might want to see both, I'm not sure.
> 
> FedEx handles this by returning this "AppliedOptions" field which has a list of options that are set, and the One Rate rate says FEDEX_ONE_RATE for that one.
> 
> So my commit handles this by just returning AppliedOptions in the meta field to the caller. This works fine for my program that I'm testing. But I'm just testing with the SDK right now, and you have a pretty clean design and I'm not sure if this is violating how you want to do the architecture between the SDK and the rest of your code.
> 
> The other way I thought of doing this is to break One Rate out as separate service types, so there would be FEDEX_ONE_RATE_2_DAY, FEDEX_ONE_RATE_OVERNIGHT, etc, so the SDK could handle everything transparently and callers would just see those different service types. The trouble with that is that FedEx doesn't see them as separate service types so the SDK would need to basically translate between the two, which wouldn't be that hard, but would add more logic in the SDK, for both rate.py and ship.py. I feel like that might be a cleaner solution as then it keeps that logic entirely in the SDK, but it still isn't ideal since it requires inventing new service types that aren't coming directly from FedEx. Ideally FedEx would just break them down into separate service types itself since that's what they should be, instead of calling it an "option", but I doubt that will happen.

Hey @nahall,
Don't sell yourself short. This is a great analysis of the edge case. 
I appreciate you being mindful of the architecture. Great use of meta. It is exactly intended for this kind of situation. Though, I agree that I would be more inclined to go for the second option and enhance anthem FedEx code to handle FedEx One rate as a separate service.

I will give it a shot and would love to get your opinion.

**Comment by danh91** [comment]
Hey @nahall ,
I merged what you had already done here.
Please open a new PR if you make new changes.

**Comment by nahall** [comment]
Great, thanks Dan, I have been testing with my changes now for a couple weeks and I haven't seen any more edge cases in the meantime.

**Pull request merged**
