### PR TITLE
make FedEx notification Format to HTML by default

### PR DESCRIPTION
**Pull request by jacobshilitz**

### CODE REVIEW

**Comment by jacobshilitz** [comment]
maybe would be good idea to expose a option on the api, but i'm not sure if its fedex only

```
notification_format: 'HTML',
```

or maybe make possible to pass settigns for fedex only

```
fedex_notification_format: 'HTML',
```

**Comment by danh91** [comment]
Hey @jacobshilitz ,

I think for now it can be added to FedEx options.
```
fedex_notification_format: 'HTML',
```

**Comment by jacobshilitz** [comment]
there are too many options and customizations in FedEx api. foramt is not so important. 
I think we should decide on a way how to expose FedEx options to API end-user.
for now, i think it should be default to `HTML`

**Comment by danh91** [comment]
> there are too many options and customizations in FedEx api. foramt is not so important. I think we should decide on a way how to expose FedEx options to API end-user. for now, i think it should be default to `HTML`

That works for me. We can just keep it defaulted to `HTML` for now.

**Review by danh91 — APPROVED** [review]
This looks good to go.
I will merge it and release new patch versions with this and your other PR

**Pull request merged**
